(defun p1 (l)
  "Parcurgere de lista pe n-nivele, cu rezultat in o lista liniara"
  (let ((r nil))
    (dolist (i l)
      (if (listp i)
        (setf r (append (p1 i) r))
        (setf r (push i r))
      )
    )
    (reverse r)
  )
) 

(defun p2 (l)
  (let ((r nil))
    (dolist (i l)
      (if (listp i)
        (list
         (setf r (reverse r))
         (setf r (push (reverse (p1 i)) r) )
        )
        (setf r (push i r))
      )
    )
    (reverse r)
  )
)
